version: '3'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-sock
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/opt/jenkins:/var/opt/jenkins
      - /var/run/docker.sock:/var/run/docker.sock